spring.application.name=placement-backend

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=false
management.health.mongo.enabled=false

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:PlaceIQ2026SuperSecretKeyForJWTTokenGenerationMustBe256BitsLong!}
jwt.expiration=${JWT_EXPIRATION:86400000}

gemini.api.key=${GEMINI_API_KEY:AIzaSyD_axhQ9If6NEqlKUi8lAGlIn7FRmxaePE}

logging.level.org.springframework.data.mongodb=ERROR
logging.level.com.placeiq=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.placeiq.api
